"""
Module: generate_mcp_module_tools_reference

Generates `backend/mcp_skill_reference/module-tools.md`, the exhaustive list of
module-contributed MCP tools that the agent skill (`mcp-server/skill/`)
ships as `references/module-tools.md`.

Responsibilities:
- Render every tool in `build_mcp_tool_manifest()` (the exact list the MCP
  server registers, including the tool each module `ReportDefinition`
  generates) grouped by contributing module, each group led by that module's
  hand-written `ModuleDefinition.mcp_guidance` (how to use the tools).
- `--check` fails when the committed file is stale; `backend/tests/
  test_mcp_skill_reference.py` runs the same comparison, so adding a tool
  without regenerating this file fails CI.

Design decisions:
- Lives in the backend because the manifest can only be built from the live
  module registry; `mcp-server/` has no backend code (separate container).
  The core-tool counterpart is `mcp-server/scripts/generate_skill_reference.py`.
- Output is deterministic (registry order, then declaration order, no
  timestamps) so a diff means a real tool change.

Usage (from `backend/`): `python scripts/generate_mcp_module_tools_reference.py [--check]`
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))  # make `app` importable when run as a script

REFERENCE_PATH = Path(__file__).resolve().parent.parent / "mcp_skill_reference" / "module-tools.md"

_HEADER = """# Module tools

<!-- GENERATED by backend/scripts/generate_mcp_module_tools_reference.py - do not edit by hand. -->

Tools contributed by modules (including one tool per module report). Each module section starts
with how to use its tools (workflow, lifecycle, gated tools), then lists every tool. Each name is
`<module_key>_<tool>`. A tool only works when its module is enabled for the
organisation or project, and the caller still needs that module's own role.
Tools marked **write** are registered only when the server runs in write mode.
Parameters marked `*` are required; `in` shows where the value is sent.
"""


def _first_sentence_block(text: str) -> str:
    """Collapses a description to its first paragraph on one line."""
    return " ".join(text.strip().split("\n\n")[0].split())


def render() -> str:
    """Builds the Markdown reference from the live module registry.

    Returns:
        The full file contents, ending in a newline.
    """
    from app.modules.registry import build_mcp_tool_manifest, get_module_registry

    manifest = build_mcp_tool_manifest()
    lines = [_HEADER]
    remaining = list(manifest)
    for key, definition in get_module_registry().items():
        tools = [t for t in remaining if t.name.startswith(f"{key}_")]
        if not tools:
            continue
        remaining = [t for t in remaining if t not in tools]
        if not definition.mcp_guidance.strip():
            raise RuntimeError(f"Module {key!r} contributes MCP tools but has no mcp_guidance (ModuleDefinition.mcp_guidance)")
        lines.append(f"## {definition.name} (`{key}`)\n")
        lines.append(f"{_first_sentence_block(definition.description)}\n")
        lines.append("### How to use these tools\n")
        lines.append(f"{definition.mcp_guidance.strip()}\n")
        lines.append("### Tool list\n")
        for tool in tools:
            kind = "write" if tool.mutates else "read"
            lines.append(f"#### `{tool.name}` ({kind})\n")
            lines.append(f"{_first_sentence_block(tool.description)}\n")
            if tool.params:
                params = ", ".join(
                    f"`{p['name']}{'*' if p.get('required') else ''}` ({p.get('type', 'string')}, in {p.get('in', 'query')})"
                    for p in tool.params
                )
                lines.append(f"Parameters: {params}\n")
    if remaining:
        # A tool whose name does not start with a registered module key cannot happen today
        # (build_mcp_tool_manifest always prefixes); fail loudly rather than silently omit it.
        raise RuntimeError(f"MCP tools not attributable to a module: {[t.name for t in remaining]}")
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: list[str]) -> int:
    """CLI entry point: writes the reference, or with `--check` verifies it.

    Args:
        argv: Command-line arguments after the program name.

    Returns:
        Process exit code (1 when `--check` finds a stale file).
    """
    content = render()
    if "--check" in argv:
        if not REFERENCE_PATH.exists() or REFERENCE_PATH.read_text() != content:
            print(f"{REFERENCE_PATH} is stale; run: python scripts/generate_mcp_module_tools_reference.py")
            return 1
        return 0
    REFERENCE_PATH.write_text(content)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
