"""
Module: routers.auth_oidc

The OIDC login flow (E-U-01): redirects the browser to an organisation's
configured identity provider, then on callback verifies the returned ID
token, provisions/resolves the local user account and syncs their org role
from IdP claims (services/oidc_provisioning.py), and issues the exact same
kind of access token the native login flow issues — so once logged in via
SSO, the resulting session is indistinguishable from a native one to the
rest of the app (token_version revocation, WebSocket expiry checks, etc. all
apply unchanged).

Deliberately not shaped as an `AuthBackend` (app/auth_backends/base.py):
that protocol's `authenticate(identifier, credential)` is a single
request/response call, but OIDC is an inherently multi-step redirect flow
(authorize redirect -> IdP login -> callback with a code -> token exchange).
"""

from __future__ import annotations

from urllib.parse import quote
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query, status
from fastapi.responses import RedirectResponse
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.config import get_settings
from app.database import get_db
from app.deps import get_client_ip
from app.models.organization import Organization
from app.security import create_access_token, create_oidc_state_token, decode_access_token
from app.services import oidc_client
from app.services.audit import log_event, log_login
from app.services.oidc_provisioning import find_or_provision_user, meets_required_group, sync_org_roles_from_claims

router = APIRouter(prefix="/api/v1/auth/oidc", tags=["auth-oidc"])
settings = get_settings()


def _redirect_uri() -> str:
    return f"{settings.public_backend_url.rstrip('/')}/api/v1/auth/oidc/callback"


def _get_sso_org_by_slug(db: Session, slug: str) -> Organization:
    org = db.scalar(select(Organization).where(Organization.slug == slug))
    if org is None or not org.sso_enabled or not org.oidc_issuer_url or not org.oidc_client_id:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "SSO is not configured for this organisation.")
    return org


@router.get("/{slug}/login")
def start_oidc_login(slug: str, client_nonce: str = Query(..., min_length=16, max_length=256), db: Session = Depends(get_db)):
    """Redirects the browser to the organisation's configured identity
    provider to begin login (E-P-03's "Sign in with SSO" button target).

    `client_nonce`: generated by the frontend and stored in its own
    `sessionStorage` *before* it ever navigates here — round-tripped through
    `state` and the eventual callback redirect so `/oidc-complete` can prove
    the token it receives belongs to this same browser's own login attempt,
    not one replayed/forwarded from someone else's (see
    `security.create_oidc_state_token`'s docstring for the full threat this
    closes).
    """
    org = _get_sso_org_by_slug(db, slug)
    discovery = oidc_client.discover(org.oidc_issuer_url)
    state = create_oidc_state_token(str(org.id), client_nonce)
    authorize_url = oidc_client.build_authorize_url(
        discovery, client_id=org.oidc_client_id, redirect_uri=_redirect_uri(), state=state,
    )
    return RedirectResponse(authorize_url, status_code=status.HTTP_302_FOUND)


@router.get("/callback")
def oidc_callback(code: str, state: str, request_ip: str = Depends(get_client_ip), db: Session = Depends(get_db)):
    """Completes login: exchanges the authorization code, verifies the ID
    token, checks the org's required-group access gate (if configured),
    provisions/resolves the user and syncs their org role, then redirects to
    the frontend with a working app access token — or, if the required-group
    gate rejects the claims, redirects with an error message instead and
    never issues a token.

    Every attempt — a failed token exchange/ID-token verification, a
    required-group denial, or a successful login — is recorded as a
    `login_events` row (same table native `/login` writes to, with the
    source IP), not just as an `audit_events` entry, so SSO logins show up
    in the same authentication-monitoring trail as native ones rather than
    being a blind spot (SOC 2 monitoring/logging hardening pass).
    """
    state_claims = decode_access_token(state)
    if (
        not state_claims
        or state_claims.get("purpose") != "oidc_state"
        or "org_id" not in state_claims
        or not state_claims.get("client_nonce")
    ):
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Invalid or expired SSO login attempt.")
    client_nonce = state_claims["client_nonce"]
    org = db.get(Organization, UUID(state_claims["org_id"]))
    if org is None or not org.sso_enabled or not org.oidc_issuer_url or not org.oidc_client_id:
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "SSO is not configured for this organisation.")

    discovery = oidc_client.discover(org.oidc_issuer_url)
    try:
        tokens = oidc_client.exchange_code_for_tokens(
            discovery, client_id=org.oidc_client_id, client_secret=org.oidc_client_secret or "",
            redirect_uri=_redirect_uri(), code=code,
        )
        claims = oidc_client.verify_id_token(
            discovery, tokens["id_token"], client_id=org.oidc_client_id, issuer_url=org.oidc_issuer_url,
        )
    except (KeyError, ValueError) as exc:
        log_login(
            db, user_id=None, email_attempted=f"(oidc login failed: {org.slug})", ip_address=request_ip, success=False,
        )
        db.commit()
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, f"SSO login failed: {exc}") from exc

    if not meets_required_group(org, claims):
        # Authenticated successfully at the IdP, but not admitted: refused
        # before any local account is provisioned or any token is issued —
        # this is a stricter, separate gate from sync_org_roles_from_claims
        # below (which only decides *which* role a user gets, never whether
        # they're let in at all).
        log_event(db, entity_type="organization", entity_id=org.id, action="oidc_login_denied_not_provisioned",
                  actor_id=None, organization_id=org.id, detail={"subject": claims.get("sub"), "email": claims.get("email")})
        log_login(
            db, user_id=None, email_attempted=claims.get("email") or "(unknown)", ip_address=request_ip, success=False,
        )
        db.commit()
        message = f"{org.name} has not provisioned you access."
        return RedirectResponse(
            f"{settings.frontend_base_url.rstrip('/')}/oidc-complete"
            f"?error=not_provisioned&message={quote(message)}&client_nonce={quote(client_nonce)}",
            status_code=status.HTTP_302_FOUND,
        )

    user = find_or_provision_user(db, claims, issuer=org.oidc_issuer_url)
    sync_org_roles_from_claims(db, user, org, claims)
    log_event(db, entity_type="user", entity_id=user.id, action="oidc_login",
              actor_id=user.id, organization_id=org.id, detail={"issuer": org.oidc_issuer_url})
    log_login(db, user_id=user.id, email_attempted=user.email, ip_address=request_ip, success=True)
    db.commit()

    app_token = create_access_token(str(user.id), token_version=user.token_version)
    # The access token travels in the URL *fragment*, not the query string:
    # fragments are never sent to the server (or any intermediate proxy) over
    # HTTP and don't land in server access logs, unlike query parameters.
    # `client_nonce` rides alongside it so OidcCompletePage can confirm this
    # redirect corresponds to the login attempt *this* browser initiated
    # before it trusts the token (see security.create_oidc_state_token).
    return RedirectResponse(
        f"{settings.frontend_base_url.rstrip('/')}/oidc-complete"
        f"#token={quote(app_token)}&client_nonce={quote(client_nonce)}",
        status_code=status.HTTP_302_FOUND,
    )
