import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Explicit sidebar (not autogenerated) so the top-level section order always
 * matches docs-website-plan.md's "Site structure" list, regardless of
 * filesystem/alphabetical ordering. Every section has real content as of
 * Phase 9 (API & Integrations nests a further "AI assistants (MCP)" category
 * inside it) - the plan's Phase 10 is polish/cross-linking/QA, not new pages.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['introduction/overview', 'introduction/use-cases'],
    },
    {
      type: 'category',
      label: 'Installation & Deployment',
      items: [
        'installation-deployment/overview',
        'installation-deployment/quick-start',
        'installation-deployment/production-deployment',
        'installation-deployment/configuration-reference',
        'installation-deployment/storage-database-and-migrations',
        'installation-deployment/tls-and-reverse-proxy',
        'installation-deployment/observability',
        'installation-deployment/scaling-and-modules',
        'installation-deployment/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/organisations-and-projects',
        'concepts/requirements-versions-and-lifecycle',
        'concepts/change-requests-and-baselines',
        'concepts/roles-groups-and-access-control',
        'concepts/custom-fields-terminology-and-templates',
        'concepts/discussions-notifications-and-audit',
      ],
    },
    {
      type: 'category',
      label: 'Core Features',
      items: [
        'core-features/requirements-management',
        'core-features/change-requests',
        'core-features/stages-and-baselining',
        'core-features/requirement-actions',
        'core-features/reports-and-export',
        'core-features/notifications-and-email',
        'core-features/file-attachments-and-shared-resources',
        'core-features/search-filtering-and-view-mode',
        'core-features/two-factor-authentication',
        'core-features/personal-access-tokens',
        'core-features/project-templates',
        'core-features/zip-export-import',
      ],
    },
    {
      type: 'category',
      label: 'Workflows',
      items: [
        'workflows/signing-in',
        'workflows/preferences-and-help',
        'workflows/organisations-and-projects',
        'workflows/authoring-and-reviewing-requirements',
        'workflows/change-requests',
        'workflows/stages-baselining-and-reviews',
        'workflows/requirement-actions',
        'workflows/files-comments-and-history',
        'workflows/reporting-and-csv-import-export',
        'workflows/notifications',
        'workflows/administering-an-organisation',
        'workflows/administering-a-project',
        'workflows/server-administration',
        'workflows/two-factor-authentication',
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      items: [
        'modules/overview',
        'modules/compliance-module',
        'modules/building-your-own-module',
        'modules/third-party-and-federated-modules',
      ],
    },
    {
      type: 'category',
      label: 'API & Integrations',
      items: [
        'api-integrations/rest-api-overview',
        'api-integrations/authenticating',
        'api-integrations/common-api-tasks',
        'api-integrations/single-sign-on',
        'api-integrations/scim-provisioning',
        {
          type: 'category',
          label: 'AI assistants (MCP)',
          items: [
            'api-integrations/ai-assistants-mcp/overview',
            'api-integrations/ai-assistants-mcp/setting-up-claude-code',
            'api-integrations/ai-assistants-mcp/setting-up-vs-code',
            'api-integrations/ai-assistants-mcp/setting-up-microsoft-copilot-studio',
            'api-integrations/ai-assistants-mcp/generic-mcp-clients',
            'api-integrations/ai-assistants-mcp/deploying-for-remote-clients',
            'api-integrations/ai-assistants-mcp/known-limitations',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Enterprise & Security',
      items: [
        'enterprise-security/encryption-and-secrets-handling',
        'enterprise-security/two-factor-auth-and-pats-security',
        'enterprise-security/soc-2-compliance-posture',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/architecture-overview',
        'reference/glossary',
        'reference/contributing',
      ],
    },
  ],
};

export default sidebars;
