import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Explicit sidebar (not autogenerated) so the top-level section order always
 * matches docs-website-plan.md's "Site structure" list, regardless of
 * filesystem/alphabetical ordering. Introduction, Installation & Deployment,
 * and Concepts have real content as of Phase 3; the remaining categories
 * still hold the Phase 1 placeholder page(s) later content phases (4-9)
 * will replace.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['introduction/overview', 'introduction/use-cases'],
    },
    {
      type: 'category',
      label: 'Installation & Deployment',
      items: [
        'installation-deployment/overview',
        'installation-deployment/quick-start',
        'installation-deployment/production-deployment',
        'installation-deployment/configuration-reference',
        'installation-deployment/storage-database-and-migrations',
        'installation-deployment/tls-and-reverse-proxy',
        'installation-deployment/observability',
        'installation-deployment/scaling-and-modules',
        'installation-deployment/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/organisations-and-projects',
        'concepts/requirements-versions-and-lifecycle',
        'concepts/change-requests-and-baselines',
        'concepts/roles-groups-and-access-control',
        'concepts/custom-fields-terminology-and-templates',
        'concepts/discussions-notifications-and-audit',
      ],
    },
    {
      type: 'category',
      label: 'Core Features',
      items: ['core-features/index'],
    },
    {
      type: 'category',
      label: 'Workflows',
      items: ['workflows/index'],
    },
    {
      type: 'category',
      label: 'Modules',
      items: ['modules/index'],
    },
    {
      type: 'category',
      label: 'API & Integrations',
      items: ['api-integrations/index'],
    },
    {
      type: 'category',
      label: 'Enterprise & Security',
      items: ['enterprise-security/index'],
    },
    {
      type: 'category',
      label: 'Reference',
      items: ['reference/index'],
    },
  ],
};

export default sidebars;
