import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Explicit sidebar (not autogenerated) so the top-level section order always
 * matches docs-website-plan.md's "Site structure" list, regardless of
 * filesystem/alphabetical ordering. Each category currently holds the
 * Phase 1 placeholder page(s) content phases (2-9) will replace.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['introduction/overview', 'introduction/use-cases'],
    },
    {
      type: 'category',
      label: 'Installation & Deployment',
      items: ['installation-deployment/overview'],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: ['concepts/index'],
    },
    {
      type: 'category',
      label: 'Core Features',
      items: ['core-features/index'],
    },
    {
      type: 'category',
      label: 'Workflows',
      items: ['workflows/index'],
    },
    {
      type: 'category',
      label: 'Modules',
      items: ['modules/index'],
    },
    {
      type: 'category',
      label: 'API & Integrations',
      items: ['api-integrations/index'],
    },
    {
      type: 'category',
      label: 'Enterprise & Security',
      items: ['enterprise-security/index'],
    },
    {
      type: 'category',
      label: 'Reference',
      items: ['reference/index'],
    },
  ],
};

export default sidebars;
