"""
Module: generate_skill_reference

Generates `mcp-server/skill/reqtrack-mcp/references/core-tools.md`, the
exhaustive list of the MCP server's own (non-module) tools shipped in the
agent skill.

Responsibilities:
- Import `server` twice in clean subprocesses (write mode off, then on) so
  write-only tools can be labelled without parsing source.
- Render name, kind (read / write / approval), first-paragraph description and
  parameters for every tool.
- `--check` fails when the committed file is stale; `tests/test_skill.py`
  runs the same comparison, so adding a tool without regenerating fails CI.

Design decisions:
- Module-contributed tools are excluded here: they only exist in the backend's
  manifest and are covered by `backend/scripts/generate_mcp_module_tools_reference.py`.
- Output is deterministic (sorted by name, no timestamps).

Usage (from `mcp-server/`): `python scripts/generate_skill_reference.py [--check]`
"""

from __future__ import annotations

import asyncio
import json
import os
import subprocess
import sys
from pathlib import Path

SERVER_DIR = Path(__file__).resolve().parent.parent
REFERENCE_PATH = SERVER_DIR / "skill" / "reqtrack-mcp" / "references" / "core-tools.md"

# Approval-type tools additionally require project + organisation AI-approval opt-in (docs/mcp-server.md).
APPROVAL_TOOLS = frozenset({"approve_requirement", "decide_change_request", "complete_requirement"})

_HEADER = """# Core tools

<!-- GENERATED by mcp-server/scripts/generate_skill_reference.py - do not edit by hand. -->

Tools every deployment has. **write** tools exist only when the server runs with
`MCP_WRITES_ENABLED`; **approval** tools additionally need the project and the
organisation to enable AI approval. Parameters marked `*` are required. Omit
`organization_id` / `project_id` when the connection sets default-scope headers.
Module-contributed tools are in `module-tools.md`.
"""


def _dump_tools() -> list[dict]:
    """Lists the tools registered by `server` in this process (child-process mode).

    Returns:
        One dict per tool: name, description, params [{name, type, required}].
    """
    sys.path.insert(0, str(SERVER_DIR))
    import server

    tools = asyncio.run(server.mcp.list_tools())
    out = []
    for tool in tools:
        schema = tool.parameters or {}
        required = set(schema.get("required", []))
        params = [
            {"name": name, "type": _schema_type(spec), "required": name in required}
            for name, spec in schema.get("properties", {}).items()
        ]
        out.append({"name": tool.name, "description": tool.description or "", "params": params})
    return out


def _schema_type(spec: dict) -> str:
    """Summarises a JSON-schema property as a short type string."""
    if "anyOf" in spec:
        parts = [_schema_type(s) for s in spec["anyOf"]]
        return " | ".join(p for p in parts if p != "null") or "any"
    if spec.get("type") == "array":
        return f"list[{_schema_type(spec.get('items', {}))}]"
    return spec.get("type", "any")


def _tools_with_writes(enabled: bool) -> list[dict]:
    """Runs this script in a clean child process to get the tool list for one write-mode setting."""
    env = {**os.environ, "MCP_WRITES_ENABLED": "1" if enabled else "0"}
    result = subprocess.run(
        [sys.executable, str(Path(__file__).resolve()), "--dump"], env=env, capture_output=True, text=True, check=True, cwd=SERVER_DIR
    )
    return json.loads(result.stdout.splitlines()[-1])


def collect() -> list[dict]:
    """Collects every core tool with its kind.

    Returns:
        Tool dicts (see `_dump_tools`) plus `kind` in read/write/approval, sorted by name.
    """
    read_names = {t["name"] for t in _tools_with_writes(False)}
    tools = _tools_with_writes(True)
    for tool in tools:
        tool["kind"] = "approval" if tool["name"] in APPROVAL_TOOLS else ("read" if tool["name"] in read_names else "write")
    return sorted(tools, key=lambda t: t["name"])


def render(tools: list[dict] | None = None) -> str:
    """Builds the Markdown reference.

    Args:
        tools: Output of `collect()`; collected when omitted.

    Returns:
        The full file contents, ending in a newline.
    """
    tools = tools if tools is not None else collect()
    lines = [_HEADER]
    for tool in tools:
        lines.append(f"## `{tool['name']}` ({tool['kind']})\n")
        lines.append(" ".join(tool["description"].strip().split("\n\n")[0].split()) + "\n")
        if tool["params"]:
            params = ", ".join(f"`{p['name']}{'*' if p['required'] else ''}` ({p['type']})" for p in tool["params"])
            lines.append(f"Parameters: {params}\n")
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: list[str]) -> int:
    """CLI entry point: writes the reference, `--check` verifies it, `--dump` prints tool JSON (internal).

    Args:
        argv: Command-line arguments after the program name.

    Returns:
        Process exit code (1 when `--check` finds a stale file).
    """
    if "--dump" in argv:
        print(json.dumps(_dump_tools()))
        return 0
    content = render()
    if "--check" in argv:
        if not REFERENCE_PATH.exists() or REFERENCE_PATH.read_text() != content:
            print(f"{REFERENCE_PATH} is stale; run: python scripts/generate_skill_reference.py")
            return 1
        return 0
    REFERENCE_PATH.write_text(content)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
