"""
Module: storage_backends.local

Local filesystem file storage backend — the default, simplest self-host
path (I-M-10). Keys are relative paths under a configured base directory;
nested directories are created automatically.
"""

from __future__ import annotations

import os
from pathlib import Path


class LocalFileStorageBackend:
    """Stores files as plain files under a base directory."""

    name = "local"

    def __init__(self, base_dir: str) -> None:
        self._base_dir = Path(base_dir)
        self._base_dir.mkdir(parents=True, exist_ok=True)

    def _confine(self, key: str) -> str:
        """Resolves `key` to an absolute path confined to the base directory.

        `key` is always generated by app/services/files.py, which sanitizes
        the client-supplied filename component (`_safe_key_component`) so
        it can never contain `/` or traversal segments before it's ever
        concatenated into a key — a prior version of that sanitization
        missed this and allowed a crafted filename to escape the
        uploading organisation's own key prefix while still passing the
        check below (see docs/decisions.md's hardening review). The check
        below remains as defense in depth, not the only guard.

        Resolves both sides with `os.path.realpath` (following symlinks)
        and compares with a plain `startswith` — the exact confinement
        idiom CodeQL's own py/path-injection guidance documents as safe.

        `save` (below) repeats this same check inline, immediately before
        its own filesystem write, rather than relying solely on this
        method's internal guard: CodeQL's py/path-injection query
        (github.com/.../security/code-scanning alerts #5/#6) flagged
        `save`'s `path.parent.mkdir(...)`/`path.write_bytes(...)` even
        though this method already guards the exact same path — it does
        not treat a check performed inside a called helper as a sanitizing
        barrier for the caller's later use of the returned value, since its
        own documented-safe example performs the check and the filesystem
        access in the same function. `read`/`delete` weren't flagged
        (CodeQL's query models writes, not reads/deletes, as the sink here)
        so they keep using this helper rather than duplicating the guard
        for no tool-verifiable benefit.

        Raises:
            ValueError: If the resolved path escapes the base directory.
        """
        base = os.path.realpath(self._base_dir)
        candidate = os.path.realpath(os.path.join(base, key))
        if candidate != base and not candidate.startswith(base + os.sep):
            raise ValueError("Invalid storage key.")
        return candidate

    def save(self, key: str, data: bytes) -> None:
        base = os.path.realpath(self._base_dir)
        candidate = os.path.realpath(os.path.join(base, key))
        if candidate != base and not candidate.startswith(base + os.sep):
            raise ValueError("Invalid storage key.")
        path = Path(candidate)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)

    def read(self, key: str) -> bytes:
        path = Path(self._confine(key))
        if not path.is_file():
            raise FileNotFoundError(key)
        return path.read_bytes()

    def delete(self, key: str) -> None:
        path = Path(self._confine(key))
        path.unlink(missing_ok=True)

    def disk_usage_percent(self) -> float:
        """Returns the percentage of disk space used on the storage volume (I-M-11)."""
        import shutil

        usage = shutil.disk_usage(self._base_dir)
        return (usage.used / usage.total) * 100
