"""
Module: storage_backends.local

Local filesystem file storage backend — the default, simplest self-host
path (I-M-10). Keys are relative paths under a configured base directory;
nested directories are created automatically.
"""

from __future__ import annotations

import os
from pathlib import Path


class LocalFileStorageBackend:
    """Stores files as plain files under a base directory."""

    name = "local"

    def __init__(self, base_dir: str) -> None:
        self._base_dir = Path(base_dir)
        self._base_dir.mkdir(parents=True, exist_ok=True)

    def _path_for(self, key: str) -> Path:
        """Resolves `key` to an absolute path confined to the base directory.

        Raises:
            ValueError: If the resolved path escapes the base directory.
        """
        # `key` is always generated by app/services/files.py, which sanitizes
        # the client-supplied filename component (`_safe_key_component`) so
        # it can never contain `/` or traversal segments before it's ever
        # concatenated into a key — a prior version of that sanitization
        # missed this and allowed a crafted filename to escape the
        # uploading organisation's own key prefix while still passing the
        # check below (see docs/decisions.md's hardening review). The
        # check here remains as defense in depth, not the only guard.
        #
        # Resolve both sides with os.path.realpath (following symlinks) and
        # compare with a plain startswith — the exact confinement idiom
        # CodeQL's own py/path-injection guidance documents as safe — rather
        # than pathlib's resolve()/is_relative_to(), which CodeQL's taint
        # tracker doesn't recognise as a sanitizing barrier for this query.
        base = os.path.realpath(self._base_dir)
        candidate = os.path.realpath(os.path.join(base, key))
        if candidate != base and not candidate.startswith(base + os.sep):
            raise ValueError("Invalid storage key.")
        return Path(candidate)

    def save(self, key: str, data: bytes) -> None:
        path = self._path_for(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)

    def read(self, key: str) -> bytes:
        path = self._path_for(key)
        if not path.is_file():
            raise FileNotFoundError(key)
        return path.read_bytes()

    def delete(self, key: str) -> None:
        path = self._path_for(key)
        path.unlink(missing_ok=True)

    def disk_usage_percent(self) -> float:
        """Returns the percentage of disk space used on the storage volume (I-M-11)."""
        import shutil

        usage = shutil.disk_usage(self._base_dir)
        return (usage.used / usage.total) * 100
